-- Autogenerated Server Side by NEXTZ DUMPER
-- Resource: mt-newjobs
-- Generated based on client-side TriggerServerEvent calls

RegisterNetEvent('mt-bus:cancelJob')
AddEventHandler('mt-bus:cancelJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-bus:cancelJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-bus:cancelJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-bus:closeMenu')
AddEventHandler('mt-bus:closeMenu', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-bus:closeMenu | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-bus:closeMenu
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-bus:finishJob')
AddEventHandler('mt-bus:finishJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-bus:finishJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-bus:finishJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-chicken:cancelJob')
AddEventHandler('mt-chicken:cancelJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-chicken:cancelJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-chicken:cancelJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-chicken:catchChicken')
AddEventHandler('mt-chicken:catchChicken', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-chicken:catchChicken | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-chicken:catchChicken
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-chicken:closeMenu')
AddEventHandler('mt-chicken:closeMenu', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-chicken:closeMenu | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-chicken:closeMenu
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-chicken:deliverChicken')
AddEventHandler('mt-chicken:deliverChicken', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-chicken:deliverChicken | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-chicken:deliverChicken
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-chicken:returnVehicle')
AddEventHandler('mt-chicken:returnVehicle', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-chicken:returnVehicle | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-chicken:returnVehicle
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-garbage:cancelJob')
AddEventHandler('mt-garbage:cancelJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-garbage:cancelJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-garbage:cancelJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-garbage:closeMenu')
AddEventHandler('mt-garbage:closeMenu', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-garbage:closeMenu | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-garbage:closeMenu
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-garbage:returnVehicle')
AddEventHandler('mt-garbage:returnVehicle', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-garbage:returnVehicle | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-garbage:returnVehicle
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-lumberjack:cancelJob')
AddEventHandler('mt-lumberjack:cancelJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-lumberjack:cancelJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-lumberjack:cancelJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-lumberjack:closeMenu')
AddEventHandler('mt-lumberjack:closeMenu', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-lumberjack:closeMenu | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-lumberjack:closeMenu
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-lumberjack:deliverWood')
AddEventHandler('mt-lumberjack:deliverWood', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-lumberjack:deliverWood | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-lumberjack:deliverWood
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-lumberjack:returnVehicle')
AddEventHandler('mt-lumberjack:returnVehicle', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-lumberjack:returnVehicle | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-lumberjack:returnVehicle
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-miner:cancelJob')
AddEventHandler('mt-miner:cancelJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-miner:cancelJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-miner:cancelJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-miner:closeMenu')
AddEventHandler('mt-miner:closeMenu', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-miner:closeMenu | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-miner:closeMenu
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-miner:deliverOre')
AddEventHandler('mt-miner:deliverOre', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-miner:deliverOre | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-miner:deliverOre
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-miner:returnVehicle')
AddEventHandler('mt-miner:returnVehicle', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-miner:returnVehicle | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-miner:returnVehicle
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-newjobs:server:saveConfig')
AddEventHandler('mt-newjobs:server:saveConfig', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-newjobs:server:saveConfig | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-newjobs:server:saveConfig
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-newjobs:server:toggleJob')
AddEventHandler('mt-newjobs:server:toggleJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-newjobs:server:toggleJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-newjobs:server:toggleJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:acceptAlert')
AddEventHandler('mt-taxi:server:acceptAlert', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:acceptAlert | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:acceptAlert
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:cancelAlert')
AddEventHandler('mt-taxi:server:cancelAlert', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:cancelAlert | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:cancelAlert
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:completeMission')
AddEventHandler('mt-taxi:server:completeMission', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:completeMission | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:completeMission
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:openStash')
AddEventHandler('mt-taxi:server:openStash', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:openStash | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:openStash
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:openWardrobe')
AddEventHandler('mt-taxi:server:openWardrobe', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:openWardrobe | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:openWardrobe
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:resolveAlert')
AddEventHandler('mt-taxi:server:resolveAlert', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:resolveAlert | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:resolveAlert
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:saveSetting')
AddEventHandler('mt-taxi:server:saveSetting', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:saveSetting | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:saveSetting
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:saveVehicle')
AddEventHandler('mt-taxi:server:saveVehicle', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:saveVehicle | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:saveVehicle
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:spawnVehicle')
AddEventHandler('mt-taxi:server:spawnVehicle', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:spawnVehicle | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:spawnVehicle
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-taxi:server:toggleDuty')
AddEventHandler('mt-taxi:server:toggleDuty', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-taxi:server:toggleDuty | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-taxi:server:toggleDuty
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-trucker:cancelJob')
AddEventHandler('mt-trucker:cancelJob', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-trucker:cancelJob | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-trucker:cancelJob
    -- Received args: ' .. json.encode(args))
end)

RegisterNetEvent('mt-trucker:completeDelivery')
AddEventHandler('mt-trucker:completeDelivery', function(...)
    local _source = source
    print('^2[NEXTZ] Event Triggered:^7 mt-trucker:completeDelivery | ID: ' .. _source)
    local args = {...}
    -- TODO: Add logic for mt-trucker:completeDelivery
    -- Received args: ' .. json.encode(args))
end)


