local JSON_FILE = "radio_config_v2.json"
local JOBS_FILE = "jobs_config.json"
local STATIONS_LIST_FILE = "config/police-stations/stations_list.json"
local Framework = nil

if Config.Framework == "esx" then
    Framework = exports["es_extended"]:getSharedObject()
elseif Config.Framework == "qbcore" then
    Framework = exports["qb-core"]:GetCoreObject()
end

local function loadRadioConfig()
    local fileData = LoadResourceFile(GetCurrentResourceName(), JSON_FILE)
    if fileData and fileData ~= "" then
        return json.decode(fileData)
    end
    return Config.CustomRadio or {}
end

local function saveRadioConfig(data)
    SaveResourceFile(GetCurrentResourceName(), JSON_FILE, json.encode(data, { indent = true }), -1)
    -- Notify all clients about the radio update
    TriggerClientEvent("origen_police:admin:radioUpdated", -1, data)
end

RegisterNetEvent("origen_police:admin:requestRadioSync")
AddEventHandler("origen_police:admin:requestRadioSync", function()
    local src = source
    local radioData = loadRadioConfig()
    TriggerClientEvent("origen_police:admin:radioUpdated", src, radioData)
end)

local function loadJobsConfig()
    local fileData = LoadResourceFile(GetCurrentResourceName(), JOBS_FILE)
    if fileData and fileData ~= "" then
        return json.decode(fileData)
    end
    -- Fallback default job
    return {
        {
            name = "police",
            label = "Police",
            isCustom = true,
            color = "#3b82f6",
            parent = "police",
            grades = {}
        }
    }
end

local function saveJobsConfig(data)
    SaveResourceFile(GetCurrentResourceName(), JOBS_FILE, json.encode(data, { indent = true }), -1)
end


local function loadStationsList()
    local fileData = LoadResourceFile(GetCurrentResourceName(), STATIONS_LIST_FILE)
    if fileData and fileData ~= "" then
        return json.decode(fileData)
    end
    return {}
end

local function loadStationData(stationName)
    local fileData = LoadResourceFile(GetCurrentResourceName(), "config/police-stations/" .. stationName .. ".json")
    if fileData and fileData ~= "" then
        return json.decode(fileData)
    end
    return {}
end

local function GenerateLuaConfig()
    local list = loadStationsList()
    local luaCode = "Config = Config or {}\n\n-- AUTO-GENERATED CONFIGURATION\n-- Do not edit this file manually if you are using the in-game Tablet UI.\n-- The tablet UI will overwrite this file!\n\nConfig.CustomStations = {\n"
    
    for stationId, stationInfo in pairs(list) do
        luaCode = luaCode .. "    ['" .. stationId .. "'] = {\n"
        luaCode = luaCode .. "        name = '" .. (stationInfo.name or stationId) .. "',\n"
        luaCode = luaCode .. "        label = '" .. (stationInfo.label or stationId) .. "',\n"
        luaCode = luaCode .. "        active = " .. tostring(stationInfo.active) .. ",\n"
        luaCode = luaCode .. "        jobs = { police = {} },\n"
        
        local markers = loadStationData(stationId)
        luaCode = luaCode .. "        markers = {\n"
        
        for mType, mList in pairs(markers) do
            luaCode = luaCode .. "            ['" .. mType .. "'] = {\n"
            for _, m in ipairs(mList) do
                local c = m.coords
                if c then
                    luaCode = luaCode .. "                {\n"
                    if #c == 4 then
                        luaCode = luaCode .. "                    coords = vector4(" .. c[1] .. ", " .. c[2] .. ", " .. c[3] .. ", " .. c[4] .. ")\n"
                    else
                        luaCode = luaCode .. "                    coords = vector3(" .. c[1] .. ", " .. c[2] .. ", " .. c[3] .. ")\n"
                    end
                    luaCode = luaCode .. "                },\n"
                end
            end
            luaCode = luaCode .. "            },\n"
        end
        luaCode = luaCode .. "        }\n"
        luaCode = luaCode .. "    },\n"
    end
    luaCode = luaCode .. "}\n\n"
    luaCode = luaCode .. "Config.Maps = Config.Maps or {}\nlocal idx = #Config.Maps + 1\nfor k, v in pairs(Config.CustomStations) do\n    Config.Maps[idx] = v.name\n    idx = idx + 1\nend\n"
    
    SaveResourceFile(GetCurrentResourceName(), "config/custom_stations.lua", luaCode, -1)
    print("^2[DEBUG] Auto-generated config/custom_stations.lua based on JSON files.^0")
end

local function saveStationsList(data)
    SaveResourceFile(GetCurrentResourceName(), STATIONS_LIST_FILE, json.encode(data, { indent = true }), -1)
    GenerateLuaConfig()
end

local function saveStationData(stationName, data)
    SaveResourceFile(GetCurrentResourceName(), "config/police-stations/" .. stationName .. ".json", json.encode(data, { indent = true }), -1)
    GenerateLuaConfig()
end


local function isAdmin(source)
    if Config.Framework == "esx" and Framework then
        local xPlayer = Framework.GetPlayerFromId(source)
        if xPlayer then
            local group = xPlayer.getGroup()
            for _, v in pairs(Config.PermissionsGroups) do
                if v == group then
                    return true
                end
            end
            if xPlayer.job and xPlayer.job.name == Config.PoliceJobName then
                local perms = Config.Permissions[Config.PoliceJobName]
                if perms and perms.AgentManagement and xPlayer.job.grade >= perms.AgentManagement then
                    return true
                end
            end
        end
    elseif Config.Framework == "qbcore" and Framework then
        local Player = Framework.Functions.GetPlayer(source)
        if Player then
            if Framework.Functions.HasPermission(source, Config.PermissionsGroups) then
                return true
            end
        end
    end
    return false
end

if Framework then
    Citizen.CreateThread(function()
        Citizen.Wait(2000)
        
        -- This is a custom callback to just check if someone is admin from client
        if Config.Framework == "esx" then
            Framework.RegisterServerCallback("origen_police:admin:checkAdminStatus", function(source, cb)
                cb(isAdmin(source))
            end)

            Framework.RegisterServerCallback("origen_police:admin:getGrades", function(source, cb)
                if not isAdmin(source) then
                    cb(false)
                    return
                end

                local radioData = loadRadioConfig()
                local jobsData = loadJobsConfig()
                cb({
                    jobs = jobsData, 
                    radio = radioData
                })
            end)

            Framework.RegisterServerCallback("origen_police:callback:GetStationsList", function(source, cb)
                print("^1[DEBUG SERVER] GetStationsList called by client!^0")
                local list = loadStationsList()
                print("^2[DEBUG] GetStationsList returning type: " .. type(list) .. "^0")
                cb(list)
            end)

            Framework.RegisterServerCallback("origen_police:callback:GetStation", function(source, cb, data)
                local stationName = type(data) == "table" and data.station or data
                print("^1[DEBUG SERVER] The escrowed script naturally called GetStation for: " .. tostring(stationName) .. "!!^0")
                local list = loadStationsList()
                local stationInfo = list[stationName] or {}
                local stationData = loadStationData(stationName)
                
                -- Merge metadata with markers
                local result = {}
                for k,v in pairs(stationInfo) do result[k] = v end
                result.markers = stationData
                if not result.jobs then result.jobs = {} end
                
                cb(result)
            end)

            Framework.RegisterServerCallback("origen_police:callback:SetActiveStation", function(source, cb, data)
            local list = loadStationsList()
            if list[data.station] then
                list[data.station].active = data.active
                saveStationsList(list)
                cb(true)
            else
                cb(false)
            end
        end)

        Framework.RegisterServerCallback("origen_police:callback:RemoveMarker", function(source, cb, data)
            local stationData = loadStationData(data.station)
            if stationData[data.markerName] and stationData[data.markerName][data.markerIndex] then
                table.remove(stationData[data.markerName], data.markerIndex)
                if #stationData[data.markerName] == 0 then
                    stationData[data.markerName] = nil
                end
                saveStationData(data.station, stationData)
                cb(true)
            else
                cb(false)
            end
        end)

        Framework.RegisterServerCallback("origen_police:callback:DeleteStation", function(source, cb, data)
            local stationName = type(data) == "table" and data.station or data
            print("^2[DEBUG] DeleteStation called for: " .. tostring(stationName) .. "^0")
            local list = loadStationsList()
            if list[stationName] then
                list[stationName] = nil
                saveStationsList(list)
                print("^2[DEBUG] Station " .. tostring(stationName) .. " deleted from list.^0")
                -- Optional: Delete the json file
                local filePath = GetResourcePath(GetCurrentResourceName()) .. "/config/police-stations/" .. stationName .. ".json"
                os.remove(filePath)
                cb(true)
            else
                print("^1[DEBUG] Station " .. tostring(stationName) .. " not found in list.^0")
                cb(false)
            end
        end)

        Framework.RegisterServerCallback("origen_police:callback:AddJobCatStation", function(source, cb, data)
            if not isAdmin(source) then cb(false) return end
            local list = loadStationsList()
            if list[data.station] then
                if not list[data.station].jobs then list[data.station].jobs = {} end
                if not list[data.station].jobs["police"] then list[data.station].jobs["police"] = {} end
                table.insert(list[data.station].jobs["police"], data.job)
                saveStationsList(list)
                cb(true)
            else
                cb(false)
            end
        end)

        Framework.RegisterServerCallback("origen_police:callback:RemoveJobCatStation", function(source, cb, data)
            if not isAdmin(source) then cb(false) return end
            local list = loadStationsList()
            if list[data.station] and list[data.station].jobs and list[data.station].jobs["police"] then
                for i, j in ipairs(list[data.station].jobs["police"]) do
                    if j == data.job then
                        table.remove(list[data.station].jobs["police"], i)
                        break
                    end
                end
                saveStationsList(list)
                cb(true)
            else
                cb(false)
            end
        end)

    elseif Config.Framework == "qbcore" then
        Framework.Functions.CreateCallback("origen_police:admin:checkAdminStatus", function(source, cb)
            cb(isAdmin(source))
        end)

        Framework.Functions.CreateCallback("origen_police:admin:getGrades", function(source, cb)
            if not isAdmin(source) then
                cb(false)
                return
            end

            local radioData = loadRadioConfig()
            local jobsData = loadJobsConfig()
            cb({
                jobs = jobsData, 
                radio = radioData
            })
        end)

        Citizen.CreateThread(function()
            Citizen.Wait(2000)
            Framework.Functions.CreateCallback("origen_police:callback:GetStationsList", function(source, cb)
                cb(loadStationsList())
            end)

            Framework.Functions.CreateCallback("origen_police:callback:GetStation", function(source, cb, data)
                local stationName = type(data) == "table" and data.station or data
                print("^2[DEBUG] GetStation (QBCore) called for: " .. tostring(stationName) .. "^0")
                local list = loadStationsList()
                local stationInfo = list[stationName] or {}
                local stationData = loadStationData(stationName)
                
                local result = {}
                for k,v in pairs(stationInfo) do result[k] = v end
                result.markers = stationData
                if not result.jobs then result.jobs = {} end
                
                cb(result)
            end)
        end)

        Framework.Functions.CreateCallback("origen_police:callback:SetActiveStation", function(source, cb, data)
            if not isAdmin(source) then cb(false) return end
            local list = loadStationsList()
            if list[data.station] then
                list[data.station].active = data.state
                saveStationsList(list)
                cb(true)
            else
                cb(false)
            end
        end)

        Framework.Functions.CreateCallback("origen_police:callback:RemoveMarker", function(source, cb, data)
            if not isAdmin(source) then cb(false) return end
            local stationData = loadStationData(data.station)
            if stationData[data.markerName] and stationData[data.markerName][data.markerIndex] then
                table.remove(stationData[data.markerName], data.markerIndex)
                if #stationData[data.markerName] == 0 then
                    stationData[data.markerName] = nil
                end
                saveStationData(data.station, stationData)
                cb(true)
            else
                cb(false)
            end
        end)

        Framework.Functions.CreateCallback("origen_police:callback:DeleteStation", function(source, cb, data)
            if not isAdmin(source) then cb(false) return end
            local stationName = type(data) == "table" and data.station or data
            print("^2[DEBUG] DeleteStation (QBCore) called for: " .. tostring(stationName) .. "^0")
            local list = loadStationsList()
            if list[stationName] then
                list[stationName] = nil
                saveStationsList(list)
                local filePath = GetResourcePath(GetCurrentResourceName()) .. "/config/police-stations/" .. stationName .. ".json"
                os.remove(filePath)
                cb(true)
            else
                cb(false)
            end
        end)

        Framework.Functions.CreateCallback("origen_police:callback:AddJobCatStation", function(source, cb, data)
            if not isAdmin(source) then cb(false) return end
            local list = loadStationsList()
            if list[data.station] then
                if not list[data.station].jobs then list[data.station].jobs = {} end
                if not list[data.station].jobs["police"] then list[data.station].jobs["police"] = {} end
                table.insert(list[data.station].jobs["police"], data.job)
                saveStationsList(list)
                cb(true)
            else
                cb(false)
            end
        end)

        Framework.Functions.CreateCallback("origen_police:callback:RemoveJobCatStation", function(source, cb, data)
            if not isAdmin(source) then cb(false) return end
            local list = loadStationsList()
            if list[data.station] and list[data.station].jobs and list[data.station].jobs["police"] then
                for i, j in ipairs(list[data.station].jobs["police"]) do
                    if j == data.job then
                        table.remove(list[data.station].jobs["police"], i)
                        break
                    end
                end
                saveStationsList(list)
                cb(true)
            else
                cb(false)
            end
        end)
    end

-- Push radio data to players on load
RegisterNetEvent("origen_police:server:OnPlayerLoaded")
AddEventHandler("origen_police:server:OnPlayerLoaded", function()
    local src = source
    local radioData = loadRadioConfig()
    TriggerClientEvent("origen_police:admin:radioUpdated", src, radioData)
end)

-- NUI Events for Jobs Management
RegisterNetEvent("origen_police:admin:CreateStation")
AddEventHandler("origen_police:admin:CreateStation", function(data)
    local src = source
    if not isAdmin(src) then return end
    print("^2[DEBUG] CreateStation called with name: " .. tostring(data.name) .. " label: " .. tostring(data.label) .. "^0")
    local list = loadStationsList()
    local stationId = data.name:lower():gsub("%s+", "-")
    if not list[stationId] then
        list[stationId] = {
            name = stationId,
            label = data.label,
            active = true,
            street = "Unknown",
            author = "Admin",
            modified = os.date("%Y-%m-%d"),
            jobs = {
                police = {}
            }
        }
        saveStationsList(list)
        saveStationData(stationId, {})
        TriggerClientEvent("origen_police:client:Notify", src, "Station created successfully!", "success")
        print("^2[DEBUG] Station " .. tostring(stationId) .. " created successfully.^0")
    else
        print("^1[DEBUG] Station " .. tostring(stationId) .. " already exists.^0")
    end
end)

RegisterNetEvent("origen_police:admin:CreateMarker")
AddEventHandler("origen_police:admin:CreateMarker", function(data)
    local src = source
    local stationData = loadStationData(data.station)
    if not stationData[data.markerName] then
        stationData[data.markerName] = {}
    end
    -- Support multiple vs single
    if not data.multiple then
        stationData[data.markerName] = {}
    end
    table.insert(stationData[data.markerName], { coords = { data.coords.x, data.coords.y, data.coords.z, data.coords.h } })
    saveStationData(data.station, stationData)
end)

RegisterNetEvent("origen_police:admin:SetMarkerPos")
AddEventHandler("origen_police:admin:SetMarkerPos", function(data)
    local src = source
    local stationData = loadStationData(data.station)
    if not stationData[data.markerName] then
        stationData[data.markerName] = {}
    end
    
    if data.multiple then
        if stationData[data.markerName][data.markerIndex] then
            stationData[data.markerName][data.markerIndex].coords = { data.coords.x, data.coords.y, data.coords.z, data.coords.h }
        end
    else
        stationData[data.markerName] = {
            { coords = { data.coords.x, data.coords.y, data.coords.z, data.coords.h } }
        }
    end
    saveStationData(data.station, stationData)
end)

RegisterNetEvent("origen_police:admin:addCategory")
AddEventHandler("origen_police:admin:addCategory", function(data)
    local src = source
    if not isAdmin(src) then return end
    local jobsData = loadJobsConfig()
    table.insert(jobsData, {
        name = data.name,
        label = data.label,
        color = data.color,
        parent = data.parent,
        isCustom = true,
        grades = {}
    })
    saveJobsConfig(jobsData)
    TriggerClientEvent("origen_police:admin:jobAdded", -1, jobsData[#jobsData])
end)

RegisterNetEvent("origen_police:admin:removeCategory")
AddEventHandler("origen_police:admin:removeCategory", function(data)
    local src = source
    if not isAdmin(src) then return end
    local jobsData = loadJobsConfig()
    for i, job in ipairs(jobsData) do
        if job.name == data.job then
            table.remove(jobsData, i)
            break
        end
    end
    saveJobsConfig(jobsData)
    TriggerClientEvent("origen_police:admin:jobRemoved", -1, data.job)
end)

RegisterNetEvent("origen_police:admin:addGrade")
AddEventHandler("origen_police:admin:addGrade", function(data)
    local src = source
    if not isAdmin(src) then return end
    local jobsData = loadJobsConfig()
    for _, job in ipairs(jobsData) do
        if job.name == data.job then
            if not job.grades then job.grades = {} end
            table.insert(job.grades, {
                grade = data.grade,
                name = data.name,
                label = data.label,
                payment = data.payment,
                isboss = data.isboss
            })
            saveJobsConfig(jobsData)
            TriggerClientEvent("origen_police:admin:gradesUpdated", -1, job.name, job.grades)
            break
        end
    end
end)

RegisterNetEvent("origen_police:admin:updateGrade")
AddEventHandler("origen_police:admin:updateGrade", function(data)
    local src = source
    if not isAdmin(src) then return end
    local jobsData = loadJobsConfig()
    for _, job in ipairs(jobsData) do
        if job.name == data.job and job.grades then
            for i, grade in ipairs(job.grades) do
                if grade.grade == data.grade then
                    job.grades[i] = {
                        grade = data.grade,
                        name = data.name,
                        label = data.label,
                        payment = data.payment,
                        isboss = data.isboss
                    }
                    saveJobsConfig(jobsData)
                    TriggerClientEvent("origen_police:admin:gradesUpdated", -1, job.name, job.grades)
                    break
                end
            end
        end
    end
end)

RegisterNetEvent("origen_police:admin:removeGrade")
AddEventHandler("origen_police:admin:removeGrade", function(data)
    local src = source
    if not isAdmin(src) then return end
    local jobsData = loadJobsConfig()
    for _, job in ipairs(jobsData) do
        if job.name == data.job and job.grades then
            for i, grade in ipairs(job.grades) do
                if grade.grade == data.grade then
                    table.remove(job.grades, i)
                    saveJobsConfig(jobsData)
                    TriggerClientEvent("origen_police:admin:gradesUpdated", -1, job.name, job.grades)
                    break
                end
            end
        end
    end
end)

-- NUI Events for Radio Management
RegisterNetEvent("origen_police:admin:addRadioCategory")
AddEventHandler("origen_police:admin:addRadioCategory", function(data)
    local src = source
    print("^2[SERVER DEBUG] origen_police:admin:addRadioCategory triggered by " .. tostring(src) .. " with data: " .. json.encode(data) .. "^0")
    if not isAdmin(src) then 
        print("^1[SERVER DEBUG] isAdmin failed for " .. tostring(src) .. "^0")
        return 
    end
    local radioData = loadRadioConfig()
    -- React sends { name = v }
    local catName = data.name or data.category
    if not catName then return end

    table.insert(radioData, { category = catName, freqs = {} })
    saveRadioConfig(radioData)
    print("^2[SERVER DEBUG] addRadioCategory success: " .. tostring(catName) .. "^0")
end)

RegisterNetEvent("origen_police:admin:removeRadioCategory")
AddEventHandler("origen_police:admin:removeRadioCategory", function(data)
    local src = source
    print("^2[SERVER DEBUG] origen_police:admin:removeRadioCategory triggered by " .. tostring(src) .. " with data: " .. json.encode(data) .. "^0")
    if not isAdmin(src) then return end
    local radioData = loadRadioConfig()
    -- React sends { category = v }
    local catName = data.category
    for i, cat in ipairs(radioData) do
        if cat.category == catName then
            table.remove(radioData, i)
            break
        end
    end
    saveRadioConfig(radioData)
    print("^2[SERVER DEBUG] removeRadioCategory success: " .. tostring(catName) .. "^0")
end)

RegisterNetEvent("origen_police:admin:addRadioChannel")
AddEventHandler("origen_police:admin:addRadioChannel", function(data)
    local src = source
    print("^2[SERVER DEBUG] origen_police:admin:addRadioChannel triggered by " .. tostring(src) .. " with data: " .. json.encode(data) .. "^0")
    if not isAdmin(src) then return end
    local radioData = loadRadioConfig()
    -- React sends { category = l, channel = v }
    local catName = data.category
    local channel = data.channel
    for i, cat in ipairs(radioData) do
        if cat.category == catName then
            if not cat.freqs then cat.freqs = {} end
            table.insert(cat.freqs, channel)
            break
        end
    end
    saveRadioConfig(radioData)
    print("^2[SERVER DEBUG] addRadioChannel success: " .. tostring(channel) .. " in " .. tostring(catName) .. "^0")
end)

RegisterNetEvent("origen_police:admin:removeRadioChannel")
AddEventHandler("origen_police:admin:removeRadioChannel", function(data)
    local src = source
    print("^2[SERVER DEBUG] origen_police:admin:removeRadioChannel triggered by " .. tostring(src) .. " with data: " .. json.encode(data) .. "^0")
    if not isAdmin(src) then return end
    local radioData = loadRadioConfig()
    -- React sends { category = v, channel = l }
    local catName = data.category
    local channel = data.channel
    for i, cat in ipairs(radioData) do
        if cat.category == catName and cat.freqs then
            for j, freq in ipairs(cat.freqs) do
                if tostring(freq) == tostring(channel) then
                    table.remove(cat.freqs, j)
                    break
                end
            end
            break
        end
    end
    saveRadioConfig(radioData)
    print("^2[SERVER DEBUG] removeRadioChannel success: " .. tostring(channel) .. " in " .. tostring(catName) .. "^0")
end)

RegisterNetEvent("origen_police:admin:reorderRadioCategories")
AddEventHandler("origen_police:admin:reorderRadioCategories", function(data)
    local src = source
    print("^2[SERVER DEBUG] origen_police:admin:reorderRadioCategories triggered by " .. tostring(src) .. " with data: " .. json.encode(data) .. "^0")
    if not isAdmin(src) then return end
    -- React sends { order = ["cat1", "cat2"] }
    if type(data.order) == "table" then
        local radioData = loadRadioConfig()
        local newRadio = {}
        for _, catName in ipairs(data.order) do
            for _, cat in ipairs(radioData) do
                if cat.category == catName then
                    table.insert(newRadio, cat)
                    break
                end
            end
        end
        saveRadioConfig(newRadio)
        print("^2[SERVER DEBUG] reorderRadioCategories success^0")
    end
end)

RegisterNetEvent("origen_police:admin:reorderRadioChannels")
AddEventHandler("origen_police:admin:reorderRadioChannels", function(data)
    local src = source
    print("^2[SERVER DEBUG] origen_police:admin:reorderRadioChannels triggered by " .. tostring(src) .. " with data: " .. json.encode(data) .. "^0")
    if not isAdmin(src) then return end
    -- React sends { category = "catName", channels = ["ch1", "ch2"] }
    local catName = data.category
    if type(data.channels) == "table" and catName then
        local radioData = loadRadioConfig()
        for _, cat in ipairs(radioData) do
            if cat.category == catName then
                cat.freqs = data.channels
                break
            end
        end
        saveRadioConfig(radioData)
        print("^2[SERVER DEBUG] reorderRadioChannels success^0")
    end
end)

AddEventHandler("onResourceStart", function(resourceName)
    if resourceName == GetCurrentResourceName() then
        Wait(1000)
        GenerateLuaConfig()
    end
end)

    end)
end
