-- LSC Color Categories mapping
GTA_COLORS = {
    ['Clasico'] = {
        { label = "Negro", index = 0 },
        { label = "Negro Carbon", index = 147 },
        { label = "Grafito", index = 1 },
        { label = "Negro Antracita", index = 11 },
        { label = "Acero Negro", index = 2 },
        { label = "Acero Oscuro", index = 3 },
        { label = "Plata", index = 4 },
        { label = "Plata Azulado", index = 5 },
        { label = "Acero Rolado", index = 6 },
        { label = "Plata Sombra", index = 7 },
        { label = "Plata Piedra", index = 8 },
        { label = "Plata Medianoche", index = 9 },
        { label = "Plata Fundido", index = 10 },
        { label = "Rojo", index = 27 },
        { label = "Rojo Torino", index = 28 },
        { label = "Rojo Formula", index = 29 },
        { label = "Rojo Fuego", index = 30 },
        { label = "Rojo Gracia", index = 31 },
        { label = "Rojo Granate", index = 32 },
        { label = "Rojo Desierto", index = 33 },
        { label = "Rojo Cabernet", index = 34 },
        { label = "Rojo Caramelo", index = 35 },
        { label = "Naranja Amanecer", index = 36 },
        { label = "Oro Clásico", index = 37 },
        { label = "Naranja", index = 38 },
        { label = "Amarillo", index = 88 },
        { label = "Amarillo Carrera", index = 89 },
        { label = "Bronce", index = 90 },
        { label = "Amarillo Paja", index = 91 },
        { label = "Verde Lima", index = 92 },
        { label = "Verde Oscuro", index = 49 },
        { label = "Verde Carrera", index = 50 },
        { label = "Verde Mar", index = 51 },
        { label = "Verde Oliva", index = 52 },
        { label = "Verde Vivo", index = 53 },
        { label = "Verde Petroleo", index = 54 },
        { label = "Azul Noche", index = 61 },
        { label = "Azul Oscuro", index = 62 },
        { label = "Azul Sajonia", index = 63 },
        { label = "Azul", index = 64 },
        { label = "Azul Marino", index = 65 },
        { label = "Azul Puerto", index = 66 },
        { label = "Azul Diamante", index = 67 },
        { label = "Azul Surf", index = 68 },
        { label = "Azul Nautico", index = 69 },
        { label = "Azul Ultra", index = 70 },
        { label = "Azul Claro", index = 73 },
        { label = "Marron Chocolate", index = 96 },
        { label = "Marron Bisonte", index = 97 },
        { label = "Madera", index = 98 },
        { label = "Marrón Oscuro", index = 99 },
        { label = "Marron Arena", index = 100 },
        { label = "Marron Castaño", index = 101 },
        { label = "Blanco Nieve", index = 111 },
        { label = "Blanco Nieve Seco", index = 112 },
        { label = "Blanco Hielo", index = 113 },
        { label = "Crema", index = 107 },
        { label = "Gris Plata", index = 114 },
    },
    ['Metalico'] = {
        { label = "Negro", index = 0 },
        { label = "Negro Carbon", index = 147 },
        { label = "Grafito", index = 1 },
        { label = "Negro Antracita", index = 11 },
        { label = "Acero Negro", index = 2 },
        { label = "Acero Oscuro", index = 3 },
        { label = "Plata", index = 4 },
        { label = "Plata Azulado", index = 5 },
        { label = "Acero Rolado", index = 6 },
        { label = "Plata Sombra", index = 7 },
        { label = "Plata Piedra", index = 8 },
        { label = "Plata Medianoche", index = 9 },
        { label = "Plata Fundido", index = 10 },
        { label = "Rojo", index = 27 },
        { label = "Rojo Torino", index = 28 },
        { label = "Rojo Formula", index = 29 },
        { label = "Rojo Fuego", index = 30 },
        { label = "Rojo Gracia", index = 31 },
        { label = "Rojo Granate", index = 32 },
        { label = "Rojo Desierto", index = 33 },
        { label = "Rojo Cabernet", index = 34 },
        { label = "Rojo Caramelo", index = 35 },
        { label = "Naranja Amanecer", index = 36 },
        { label = "Oro Clásico", index = 37 },
        { label = "Naranja", index = 38 },
        { label = "Amarillo", index = 88 },
        { label = "Amarillo Carrera", index = 89 },
        { label = "Bronce", index = 90 },
        { label = "Amarillo Paja", index = 91 },
        { label = "Verde Lima", index = 92 },
        { label = "Verde Oscuro", index = 49 },
        { label = "Verde Carrera", index = 50 },
        { label = "Verde Mar", index = 51 },
        { label = "Verde Oliva", index = 52 },
        { label = "Verde Vivo", index = 53 },
        { label = "Verde Petroleo", index = 54 },
        { label = "Azul Noche", index = 61 },
        { label = "Azul Oscuro", index = 62 },
        { label = "Azul Sajonia", index = 63 },
        { label = "Azul", index = 64 },
        { label = "Azul Marino", index = 65 },
        { label = "Azul Puerto", index = 66 },
        { label = "Azul Diamante", index = 67 },
        { label = "Azul Surf", index = 68 },
        { label = "Azul Nautico", index = 69 },
        { label = "Azul Ultra", index = 70 },
        { label = "Azul Claro", index = 73 },
        { label = "Marron Chocolate", index = 96 },
        { label = "Marron Bisonte", index = 97 },
        { label = "Madera", index = 98 },
        { label = "Marrón Oscuro", index = 99 },
        { label = "Marron Arena", index = 100 },
        { label = "Marron Castaño", index = 101 },
        { label = "Blanco Nieve", index = 111 },
        { label = "Blanco Nieve Seco", index = 112 },
        { label = "Blanco Hielo", index = 113 },
        { label = "Crema", index = 107 },
        { label = "Gris Plata", index = 114 },
    },
    ['Mate'] = {
        { label = "Negro", index = 12 },
        { label = "Gris", index = 13 },
        { label = "Gris Claro", index = 14 },
        { label = "Blanco Hielo", index = 131 },
        { label = "Rojo", index = 39 },
        { label = "Rojo Oscuro", index = 40 },
        { label = "Naranja", index = 41 },
        { label = "Amarillo", index = 42 },
        { label = "Verde", index = 128 },
        { label = "Verde Oscuro", index = 151 },
        { label = "Verde Bosque", index = 152 },
        { label = "Verde Oliva", index = 153 },
        { label = "Azul", index = 55 },
        { label = "Azul Oscuro", index = 82 },
        { label = "Azul Marino", index = 83 },
        { label = "Azul Medianoche", index = 84 },
        { label = "Marron", index = 129 },
        { label = "Desierto", index = 154 },
        { label = "Beige Desierto", index = 155 },
        { label = "Verde Follaje", index = 150 },
    },
    ['Metales'] = {
        { label = "Acero Cepillado", index = 117 },
        { label = "Acero Negro Cepillado", index = 118 },
        { label = "Aluminio Cepillado", index = 119 },
        { label = "Oro Puro", index = 158 },
        { label = "Oro Cepillado", index = 159 },
    },
    ['Cromo'] = {
        { label = "Cromado", index = 120 },
    }
}
