Config = Config or {}

-- AUTO-GENERATED CONFIGURATION
-- Do not edit this file manually if you are using the in-game Tablet UI.
-- The tablet UI will overwrite this file!

Config.CustomStations = {
    ['colonyislandstation'] = {
        name = 'colonyislandstation',
        label = 'Colony Island Station',
        active = true,
        jobs = { police = {} },
        markers = {
            ['RequestVehicle'] = {
                {
                    coords = vector4(5654.531738, -3172.760498, 8.706177, 90.708656)
                },
            },
        }
    },
}

Config.Maps = Config.Maps or {}
local idx = #Config.Maps + 1
for k, v in pairs(Config.CustomStations) do
    Config.Maps[idx] = v.name
    idx = idx + 1
end
